"""プラグインON/OFFのG-codeと診断ログを突き合わせ、issue15の検証レポートを生成する。"""

import argparse
import hashlib
import json
import math
import re
import sys
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path


DIAGNOSTIC_MAX_BYTES = 5 * 1024 * 1024

HEADER_LAYER = -1

# 比較対象から落とすコメント行。前半は同じ入力でも実行ごとに変わるもの、
# 後半はツールパスが変われば必ず変わる派生値。派生値の増減は押出種別ごとの
# 集計と印刷サマリーで評価する。
COMMENT_DROP_PATTERNS = (
    # 日付と時刻はゼロ埋めされないことがある（例: 2026-8-21 at 1:19:29）。
    re.compile(r"^; generated by .* on \d{1,4}-\d{1,2}-\d{1,2} at \d{1,2}:\d{2}:\d{2}"),
    re.compile(r"^;\s*(?:source[_ ]file|input[_ ]file|filename)\s*[:=]", re.IGNORECASE),
    re.compile(r"^;.*(?:/Users/|/private/|/tmp/|/var/folders/)"),
    # 押出幅は同じ値でも区間の切れ目で再出力される。幅が実際に変われば
    # 押出量と経路長に出るので、この行自体は比較対象にしない。
    re.compile(r"^;WIDTH:", re.IGNORECASE),
    # プラグイン設定のダンプはON/OFFで異なって当然で、ツールパスの差ではない。
    re.compile(
        r"^;\s*(?:print_plugin_config_overrides|different_settings_to_system)\s*=",
    ),
    re.compile(r"^;\s*(?:total\s+)?filament\s+(?:used|cost)\b", re.IGNORECASE),
    re.compile(
        r"^;\s*estimated\s+(?:first\s+layer\s+)?printing\s+time\b", re.IGNORECASE
    ),
    re.compile(r"^;\s*(?:total\s+estimated|model\s+printing)\s+time\b", re.IGNORECASE),
)

# 各レイヤへ残時間を書き込む進捗コマンド。残すと補強と無関係なレイヤまで
# 差分と判定されてしまう。
PROGRESS_COMMAND = "M73"

SUMMARY_PATTERNS = {
    "filament_used_mm": re.compile(r"^;\s*filament used \[mm\]\s*=\s*(.+)$"),
    "filament_used_cm3": re.compile(r"^;\s*filament used \[cm3\]\s*=\s*(.+)$"),
    "estimated_time": re.compile(
        r"^;\s*estimated printing time \(normal mode\)\s*=\s*(.+)$"
    ),
}

THUMBNAIL_START = re.compile(r"^;\s*thumbnail(?:_JPG|_QOI)?\s+begin", re.IGNORECASE)
THUMBNAIL_END = re.compile(r"^;\s*thumbnail(?:_JPG|_QOI)?\s+end", re.IGNORECASE)

OBJECT_NAME_SUFFIX = re.compile(r"\.stl_id_\d+_copy_\d+$", re.IGNORECASE)


class ComparisonError(RuntimeError):
    pass


@dataclass
class MoveStats:
    extrusion_mm: float = 0.0
    extrude_distance_mm: float = 0.0
    travel_distance_mm: float = 0.0
    retraction_mm: float = 0.0
    extrude_moves: int = 0

    def as_dict(self):
        return {
            "extrusion_mm": round(self.extrusion_mm, 5),
            "extrude_distance_mm": round(self.extrude_distance_mm, 4),
            "travel_distance_mm": round(self.travel_distance_mm, 4),
            "retraction_mm": round(self.retraction_mm, 5),
            "extrude_moves": self.extrude_moves,
        }


@dataclass
class MachineState:
    x: float = 0.0
    y: float = 0.0
    z: float = 0.0
    absolute_xyz: bool = True
    absolute_e: bool = True
    tool: int = 0
    e_by_tool: dict = field(default_factory=lambda: defaultdict(float))


@dataclass
class GcodeAnalysis:
    stats: dict
    line_digests: dict
    line_counts: dict
    objects: set
    layer_count: int
    summary: dict = field(default_factory=dict)

    def object_names(self):
        return {name for name in self.objects if name is not None}


def fixture_name_from_marker(marker_name):
    """EXCLUDE_OBJECTのNAMEからフィクスチャ名を復元する。

    `matrix-circle-through-0.stl_id_0_copy_0` や、小数角度を含む
    `direction-circle-through-0.1.stl_id_0_copy_0` を扱う。
    """
    stripped = OBJECT_NAME_SUFFIX.sub("", marker_name)
    if stripped == marker_name and marker_name.endswith(".stl"):
        stripped = marker_name[:-4]
    return stripped


def _strip_comment(line):
    index = line.find(";")
    return line if index < 0 else line[:index]


def _parse_params(text):
    params = {}
    for token in text.split():
        letter = token[0].upper()
        if not letter.isalpha():
            continue
        try:
            params[letter] = float(token[1:])
        except ValueError:
            continue
    return params


def _marker_name(line, prefix):
    remainder = line[len(prefix) :].strip()
    for token in remainder.split():
        if token.upper().startswith("NAME="):
            return token[5:]
    return None


def _arc_length(state, params, clockwise):
    if "I" not in params and "J" not in params:
        if "R" in params:
            raise ComparisonError("R指定の円弧には未対応です")
        raise ComparisonError("円弧にI/Jオフセットがありません")
    offset_i = params.get("I", 0.0)
    offset_j = params.get("J", 0.0)
    center_x = state.x + offset_i
    center_y = state.y + offset_j
    radius = math.hypot(offset_i, offset_j)
    if radius == 0.0:
        return 0.0
    end_x = params.get("X", state.x)
    end_y = params.get("Y", state.y)
    start_angle = math.atan2(state.y - center_y, state.x - center_x)
    end_angle = math.atan2(end_y - center_y, end_x - center_x)
    sweep = start_angle - end_angle if clockwise else end_angle - start_angle
    # 始終点が一致する円弧は全周を指す。
    if sweep <= 1e-12:
        sweep += 2.0 * math.pi
    return radius * sweep


def _record_move(stats, key, distance, delta_e):
    entry = stats[key]
    if delta_e > 0.0:
        entry.extrusion_mm += delta_e
        entry.extrude_distance_mm += distance
        entry.extrude_moves += 1
    elif delta_e < 0.0:
        entry.retraction_mm += -delta_e
        entry.travel_distance_mm += distance
    else:
        entry.travel_distance_mm += distance


def _delta_e(state, params):
    if "E" not in params:
        return 0.0
    value = params["E"]
    if state.absolute_e:
        previous = state.e_by_tool[state.tool]
        state.e_by_tool[state.tool] = value
        return value - previous
    state.e_by_tool[state.tool] += value
    return value


def normalize_line(line):
    """比較対象として残す行を返す。落とす行はNoneを返す。

    G-codeの大半は移動コマンドなので、正規表現はコメント行に限って評価する。
    """
    if line.startswith(";"):
        for pattern in COMMENT_DROP_PATTERNS:
            if pattern.search(line):
                return None
        return line
    if line == PROGRESS_COMMAND or line.startswith(PROGRESS_COMMAND + " "):
        return None
    return line


def parse_gcode(text):
    state = MachineState()
    stats = defaultdict(MoveStats)
    digests = defaultdict(lambda: hashlib.blake2b(digest_size=16))
    counts = defaultdict(int)
    objects = {None}
    layer = HEADER_LAYER
    current_type = ""
    current_object = None
    in_thumbnail = False
    open_object = None
    summary = {}

    for raw in text.splitlines():
        line = raw.strip()
        if not line:
            continue

        is_comment = line.startswith(";")

        if is_comment:
            if THUMBNAIL_START.match(line):
                in_thumbnail = True
                continue
            if THUMBNAIL_END.match(line):
                in_thumbnail = False
                continue
        if in_thumbnail:
            continue

        if line.startswith(";LAYER_CHANGE"):
            layer += 1
            current_type = ""
        elif line.startswith(";TYPE:"):
            current_type = line[len(";TYPE:") :].strip()
        elif line.startswith("EXCLUDE_OBJECT_START"):
            name = _marker_name(line, "EXCLUDE_OBJECT_START")
            if name is None:
                raise ComparisonError(f"EXCLUDE_OBJECT_STARTにNAMEがありません: {line}")
            if open_object is not None:
                raise ComparisonError(
                    f"EXCLUDE_OBJECT_STARTが入れ子になっています: {open_object} → {name}"
                )
            open_object = name
            current_object = fixture_name_from_marker(name)
            objects.add(current_object)
        elif line.startswith("EXCLUDE_OBJECT_END"):
            name = _marker_name(line, "EXCLUDE_OBJECT_END")
            if open_object is None:
                raise ComparisonError(f"対応するSTARTのないENDです: {line}")
            if name is not None and name != open_object:
                raise ComparisonError(
                    f"EXCLUDE_OBJECTのSTART/ENDが一致しません: {open_object} / {name}"
                )
            open_object = None
            current_object = None

        if is_comment:
            for name, pattern in SUMMARY_PATTERNS.items():
                if name in summary:
                    continue
                matched = pattern.match(line)
                if matched:
                    summary[name] = matched.group(1).strip()

        normalized = normalize_line(line)
        if normalized is not None:
            # 行の実体は保持しない。一致判定にはダイジェストで足りる。
            key = (current_object, layer)
            digests[key].update(normalized.encode("utf-8"))
            digests[key].update(b"\n")
            counts[key] += 1

        payload = _strip_comment(line).strip()
        if not payload:
            continue
        command = payload.split(None, 1)[0].upper()
        argument_text = payload[len(command) :]

        if command in ("G0", "G1"):
            params = _parse_params(argument_text)
            new_x = _axis(state.x, params.get("X"), state.absolute_xyz)
            new_y = _axis(state.y, params.get("Y"), state.absolute_xyz)
            new_z = _axis(state.z, params.get("Z"), state.absolute_xyz)
            distance = math.hypot(new_x - state.x, new_y - state.y)
            delta = _delta_e(state, params)
            _record_move(stats, (current_object, layer, current_type), distance, delta)
            state.x, state.y, state.z = new_x, new_y, new_z
        elif command in ("G2", "G3"):
            params = _parse_params(argument_text)
            distance = _arc_length(state, params, command == "G2")
            delta = _delta_e(state, params)
            _record_move(stats, (current_object, layer, current_type), distance, delta)
            state.x = _axis(state.x, params.get("X"), state.absolute_xyz)
            state.y = _axis(state.y, params.get("Y"), state.absolute_xyz)
            state.z = _axis(state.z, params.get("Z"), state.absolute_xyz)
        elif command == "G90":
            state.absolute_xyz = True
        elif command == "G91":
            state.absolute_xyz = False
        elif command == "M82":
            state.absolute_e = True
        elif command == "M83":
            state.absolute_e = False
        elif command == "G92":
            params = _parse_params(argument_text)
            if "E" in params:
                state.e_by_tool[state.tool] = params["E"]
            if "X" in params:
                state.x = params["X"]
            if "Y" in params:
                state.y = params["Y"]
            if "Z" in params:
                state.z = params["Z"]
        elif re.fullmatch(r"T\d+", command):
            state.tool = int(command[1:])

    if open_object is not None:
        raise ComparisonError(f"EXCLUDE_OBJECT_ENDがありません: {open_object}")

    return GcodeAnalysis(
        stats=dict(stats),
        line_digests={key: value.hexdigest() for key, value in digests.items()},
        line_counts=dict(counts),
        objects=objects,
        layer_count=layer + 1,
        summary=summary,
    )


def _axis(current, value, absolute):
    if value is None:
        return current
    return value if absolute else current + value


def load_diagnostics(path, *, max_bytes=DIAGNOSTIC_MAX_BYTES):
    size = path.stat().st_size
    events = []
    for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        stripped = line.strip()
        if not stripped:
            continue
        try:
            events.append(json.loads(stripped))
        except json.JSONDecodeError as error:
            raise ComparisonError(
                f"診断ログの{number}行目が壊れています: {error}"
            ) from error
    return {"events": events, "size_bytes": size, "at_size_cap": size >= max_bytes}


def collect_reinforcement_targets(events, *, expected_fixtures=None):
    """診断から補強対象レイヤを確定する。

    G-codeの差分から対象を逆算すると循環論法になるため、必ず診断側を基準にする。
    """
    targets = {}
    seen_objects = set()
    for event in events:
        details = event.get("details") or {}
        name = details.get("model_object_name")
        code = event.get("code")
        if code in ("object_detection_completed", "reinforcement_completed"):
            if not name:
                raise ComparisonError(
                    "診断にmodel_object_nameがありません。"
                    "モデル名を記録するwheelで再検証してください"
                )
            seen_objects.add(fixture_name_from_marker(name))
        if code != "reinforcement_completed":
            continue
        fixture = fixture_name_from_marker(name)
        if fixture in targets:
            raise ComparisonError(
                f"reinforcement_completedが重複しています: {fixture}"
            )
        layers = {}
        for entry in details.get("reinforced_layers") or ():
            layers[int(entry["layer_index"])] = {
                "print_z_mm": entry.get("print_z_mm"),
                "bbox_mm": entry.get("bbox_mm"),
                "region_count": entry.get("region_count"),
            }
        declared = details.get("reinforced_layer_count")
        if declared is not None and layers and len(layers) != int(declared):
            raise ComparisonError(
                f"{fixture}の補強レイヤ数が一致しません: "
                f"宣言{declared}件、明細{len(layers)}件"
            )
        targets[fixture] = {
            "layers": layers,
            "reinforced_layer_count": declared,
            "target_region_count": details.get("target_region_count"),
            "solid_surface_count": details.get("solid_surface_count"),
            "changed_collection_count": details.get("changed_collection_count"),
        }

    if expected_fixtures is not None:
        missing = sorted(set(expected_fixtures) - seen_objects)
        if missing:
            raise ComparisonError(
                "診断に現れないフィクスチャがあります（ログ切り詰めの可能性）: "
                + ", ".join(missing)
            )
    return targets


def collect_detection_summary(events):
    summary = {}
    for event in events:
        if event.get("code") != "object_detection_completed":
            continue
        details = event.get("details") or {}
        fixture = fixture_name_from_marker(details.get("model_object_name") or "")
        summary[fixture] = {
            "candidate_count": details.get("candidate_count"),
            "accepted_count": details.get("accepted_count"),
            "excluded_count": details.get("excluded_count"),
            "volume_count": details.get("volume_count"),
        }
    return summary


def collect_problem_events(events):
    return [
        event
        for event in events
        if str(event.get("level", "")).lower() in ("warning", "error")
    ]


def scan_python_log(path, *, offset=0):
    """GUI実行後に追記された範囲だけを見る。

    過去実行の解消済みエラーを今回の失敗として拾わないための制限。
    """
    if not path.is_file():
        return []
    with path.open("r", encoding="utf-8", errors="replace") as stream:
        stream.seek(offset)
        content = stream.read()
    entries = []
    current = []
    for line in content.splitlines():
        if line.startswith("Traceback"):
            if current:
                entries.append("\n".join(current))
            current = [line]
        elif _looks_like_exception(line):
            # tracebackの最終行なら同じブロックに属する。単独の例外行は1件として扱う。
            current.append(line)
            entries.append("\n".join(current))
            current = []
        elif current:
            current.append(line)
    if current:
        entries.append("\n".join(current))
    return entries


def _looks_like_exception(line):
    return bool(re.match(r"^[A-Za-z_][A-Za-z0-9_.]*(?:Error|Exception|Warning):", line))


def compare_analyses(on, off, targets):
    keys = set(on.line_digests) | set(off.line_digests)
    unexpected = []
    expected = []
    for key in sorted(keys, key=lambda item: (item[0] or "", item[1])):
        fixture, layer = key
        if on.line_digests.get(key) == off.line_digests.get(key):
            continue
        target_layers = (targets.get(fixture) or {}).get("layers") or {}
        record = {
            "fixture": fixture,
            "layer": layer,
            "on_line_count": on.line_counts.get(key, 0),
            "off_line_count": off.line_counts.get(key, 0),
        }
        if fixture is not None and layer in target_layers:
            record["print_z_mm"] = target_layers[layer].get("print_z_mm")
            expected.append(record)
        else:
            unexpected.append(record)
    return {"expected": expected, "unexpected": unexpected}


def aggregate_by_type(analysis):
    totals = defaultdict(lambda: defaultdict(MoveStats))
    for (fixture, _layer, type_name), value in analysis.stats.items():
        entry = totals[fixture][type_name]
        entry.extrusion_mm += value.extrusion_mm
        entry.extrude_distance_mm += value.extrude_distance_mm
        entry.travel_distance_mm += value.travel_distance_mm
        entry.retraction_mm += value.retraction_mm
        entry.extrude_moves += value.extrude_moves
    return totals


def diff_by_type(on, off):
    on_totals = aggregate_by_type(on)
    off_totals = aggregate_by_type(off)
    fixtures = set(on_totals) | set(off_totals)
    result = {}
    for fixture in fixtures:
        types = set(on_totals.get(fixture, {})) | set(off_totals.get(fixture, {}))
        entries = {}
        for type_name in types:
            on_value = on_totals.get(fixture, {}).get(type_name, MoveStats())
            off_value = off_totals.get(fixture, {}).get(type_name, MoveStats())
            delta_extrusion = on_value.extrusion_mm - off_value.extrusion_mm
            delta_distance = (
                on_value.extrude_distance_mm - off_value.extrude_distance_mm
            )
            if abs(delta_extrusion) < 1e-9 and abs(delta_distance) < 1e-9:
                continue
            entries[type_name] = {
                "on": on_value.as_dict(),
                "off": off_value.as_dict(),
                "delta_extrusion_mm": round(delta_extrusion, 5),
                "delta_extrude_distance_mm": round(delta_distance, 4),
            }
        if entries:
            result[fixture] = entries
    return result


def parse_fixture_axes(fixture):
    parts = fixture.split("-")
    if len(parts) < 4 or parts[0] != "matrix":
        return None
    return {"shape": parts[1], "end_kind": parts[2], "angle": parts[3]}


def render_report(context):
    on = context["on"]
    off = context["off"]
    targets = context["targets"]
    detection = context["detection"]
    comparison = context["comparison"]
    type_diff = context["type_diff"]

    out = ["# issue15 OrcaSlicer統合検証レポート", ""]

    out += ["## 検証環境", ""]
    for key, value in context["environment"].items():
        out.append(f"- {key}: {value}")
    out.append("")
    out.append(
        f"- 比較基準: {context['baseline_kind']}"
    )
    out.append("")

    out += ["## 受け入れ条件の判定", ""]
    checks = context["checks"]
    out.append("| 条件 | 判定 | 備考 |")
    out.append("| --- | --- | --- |")
    for name, (passed, note) in checks.items():
        out.append(f"| {name} | {'PASS' if passed else 'FAIL'} | {note} |")
    out.append("")

    out += ["## 角度・形状・端種別ごとの結果", ""]
    out.append(
        "| フィクスチャ | 形状 | 端 | 角度 | 検出 | 採用 | 補強レイヤ | ソリッド面 |"
    )
    out.append("| --- | --- | --- | --- | --- | --- | --- | --- |")
    for fixture in sorted(set(detection) | set(targets)):
        axes = parse_fixture_axes(fixture) or {}
        detected = detection.get(fixture, {})
        target = targets.get(fixture, {})
        out.append(
            "| {fixture} | {shape} | {end} | {angle} | {candidate} | {accepted} "
            "| {layers} | {surfaces} |".format(
                fixture=fixture,
                shape=axes.get("shape", "-"),
                end=axes.get("end_kind", "-"),
                angle=axes.get("angle", "-"),
                candidate=detected.get("candidate_count", "-"),
                accepted=detected.get("accepted_count", "-"),
                layers=target.get("reinforced_layer_count", 0),
                surfaces=target.get("solid_surface_count", "-"),
            )
        )
    out.append("")

    out += ["## 押出種別ごとの差分", ""]
    if not type_diff:
        out.append("差分なし。")
    else:
        out.append("| フィクスチャ | 種別 | ON押出(mm) | OFF押出(mm) | 差分(mm) |")
        out.append("| --- | --- | --- | --- | --- |")
        for fixture in sorted(type_diff, key=lambda value: value or ""):
            for type_name, entry in sorted(type_diff[fixture].items()):
                out.append(
                    "| {fixture} | {type_name} | {on} | {off} | {delta} |".format(
                        fixture=fixture if fixture is not None else "(非オブジェクト区間)",
                        type_name=type_name or "(種別なし)",
                        on=entry["on"]["extrusion_mm"],
                        off=entry["off"]["extrusion_mm"],
                        delta=entry["delta_extrusion_mm"],
                    )
                )
    out.append("")

    out += ["## 非対象領域の差分", ""]
    if not comparison["unexpected"]:
        out.append("補強対象レイヤ以外に差分はありません。")
    else:
        out.append("| フィクスチャ | レイヤ | ON行数 | OFF行数 |")
        out.append("| --- | --- | --- | --- |")
        for record in comparison["unexpected"]:
            out.append(
                "| {fixture} | {layer} | {on} | {off} |".format(
                    fixture=record["fixture"]
                    if record["fixture"] is not None
                    else "(非オブジェクト区間)",
                    layer=record["layer"],
                    on=record["on_line_count"],
                    off=record["off_line_count"],
                )
            )
    out.append("")
    out.append(
        "判定はレイヤ単位で行っている。診断へ記録した補強領域のbboxはモデル座標系のため、"
        "G-codeのプレート座標系との対応付けが必要で、レイヤ内の領域単位判定は未対応。"
    )
    out.append("")

    out += ["## Python例外と診断の警告", ""]
    problems = context["problems"]
    tracebacks = context["tracebacks"]
    if not problems and not tracebacks:
        out.append("警告・エラー・例外はありません。")
    else:
        for event in problems:
            out.append(
                f"- [{event.get('level')}] {event.get('code')}: {event.get('message')}"
            )
        for entry in tracebacks:
            out.append("")
            out.append("```")
            out.append(entry)
            out.append("```")
    out.append("")

    out += ["## 印刷サマリーの比較", ""]
    summary_labels = {
        "filament_used_mm": "フィラメント使用量(mm)",
        "filament_used_cm3": "フィラメント使用量(cm3)",
        "estimated_time": "印刷時間見積り",
    }
    out.append("| 項目 | ON | OFF |")
    out.append("| --- | --- | --- |")
    for key, label in summary_labels.items():
        out.append(
            f"| {label} | {on.summary.get(key, '-')} | {off.summary.get(key, '-')} |"
        )
    out.append("")

    out += ["## 集計メタデータ", ""]
    out.append(f"- ONレイヤ数: {on.layer_count}")
    out.append(f"- OFFレイヤ数: {off.layer_count}")
    out.append(f"- ONオブジェクト数: {len(on.object_names())}")
    out.append(f"- OFFオブジェクト数: {len(off.object_names())}")
    out.append(f"- 診断サイズ: {context['diagnostics']['size_bytes']}バイト")
    out.append("")

    return "\n".join(out)


def build_context(args):
    on = parse_gcode(args.on_gcode.read_text(encoding="utf-8", errors="replace"))
    off = parse_gcode(args.off_gcode.read_text(encoding="utf-8", errors="replace"))

    expected_fixtures = None
    if args.objects is not None:
        payload = json.loads(args.objects.read_text(encoding="utf-8"))
        expected_fixtures = payload.get("fixtures")

    diagnostics = load_diagnostics(args.diagnostics)
    events = diagnostics["events"]
    targets = collect_reinforcement_targets(events, expected_fixtures=expected_fixtures)
    detection = collect_detection_summary(events)
    problems = collect_problem_events(events)
    tracebacks = (
        scan_python_log(args.python_log, offset=args.python_log_offset)
        if args.python_log is not None
        else []
    )

    comparison = compare_analyses(on, off, targets)
    type_diff = diff_by_type(on, off)

    on_objects = on.object_names()
    off_objects = off.object_names()
    object_mismatch = sorted(on_objects ^ off_objects)

    fixture_count_ok = True
    fixture_note = f"{len(on_objects)}件"
    if expected_fixtures is not None:
        missing = sorted(set(expected_fixtures) - on_objects)
        fixture_count_ok = not missing
        if missing:
            fixture_note = "不足: " + ", ".join(missing)

    checks = {
        "角度・端種別ごとの検出と補強を記録": (
            bool(detection),
            f"{len(detection)}件の検出結果を記録",
        ),
        "非対象領域に意図しない差分がない": (
            not comparison["unexpected"],
            f"{len(comparison['unexpected'])}件の想定外差分",
        ),
        "ON/OFFで対象オブジェクトが一致": (
            not object_mismatch,
            "不一致: " + ", ".join(object_mismatch) if object_mismatch else "一致",
        ),
        "検証対象フィクスチャが揃っている": (fixture_count_ok, fixture_note),
        "Python例外がない": (
            not tracebacks,
            f"{len(tracebacks)}件のtraceback",
        ),
        "診断に警告・エラーがない": (
            not problems,
            f"{len(problems)}件",
        ),
        "診断ログが切り詰められていない": (
            not diagnostics["at_size_cap"],
            f"{diagnostics['size_bytes']}バイト",
        ),
    }

    environment = {
        "OrcaSlicerバージョン": args.orcaslicer_version,
        "OrcaSlicerビルド": args.orcaslicer_build,
        "対応保証コミット": args.supported_commit,
        "プラグインバージョン": args.plugin_version,
        "ONのG-code": str(args.on_gcode),
        "OFFのG-code": str(args.off_gcode),
        "診断ログ": str(args.diagnostics),
    }

    return {
        "on": on,
        "off": off,
        "targets": targets,
        "detection": detection,
        "problems": problems,
        "tracebacks": tracebacks,
        "comparison": comparison,
        "type_diff": type_diff,
        "checks": checks,
        "environment": environment,
        "diagnostics": diagnostics,
        "baseline_kind": args.baseline_kind,
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--on-gcode", type=Path, required=True)
    parser.add_argument("--off-gcode", type=Path, required=True)
    parser.add_argument("--diagnostics", type=Path, required=True)
    parser.add_argument("--objects", type=Path, default=None)
    parser.add_argument("--python-log", type=Path, default=None)
    parser.add_argument("--python-log-offset", type=int, default=0)
    parser.add_argument("--output", type=Path, default=None)
    parser.add_argument("--json-output", type=Path, default=None)
    parser.add_argument(
        "--baseline-kind",
        default="GUI-OFF（solid_reinforcement無効）",
        help="OFF側G-codeの取得方法。CLIベースラインを使う場合は明示する",
    )
    parser.add_argument("--orcaslicer-version", default="2.5.0-dev")
    parser.add_argument("--orcaslicer-build", default="872c660c")
    parser.add_argument(
        "--supported-commit", default="f5f3d2221dd929360407aa2ae6759302a8d2c575"
    )
    parser.add_argument("--plugin-version", default="0.1.0")
    args = parser.parse_args()

    try:
        context = build_context(args)
    except ComparisonError as error:
        print(f"エラー: {error}", file=sys.stderr)
        return 1

    report = render_report(context)
    if args.output is not None:
        args.output.write_text(report + "\n", encoding="utf-8")
        print(f"レポート: {args.output}")
    else:
        print(report)

    if args.json_output is not None:
        payload = {
            "checks": {
                name: {"passed": passed, "note": note}
                for name, (passed, note) in context["checks"].items()
            },
            "targets": context["targets"],
            "detection": context["detection"],
            "comparison": context["comparison"],
            "type_diff": context["type_diff"],
            "environment": context["environment"],
        }
        args.json_output.write_text(
            json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
        )

    return 0 if all(passed for passed, _ in context["checks"].values()) else 2


if __name__ == "__main__":
    raise SystemExit(main())
